### ISSUE TITLE
Precomile fails on 1.11 rc2, on osx

### ISSUE THREAD

**Issue by jonalm** [KristofferC/OhMyREPL.jl#367]
OhMyREPL worked fine on 1.11 rc1 but after I updated to rc2 then precompilation failed. Has anybody else experienced that?

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.0-rc2 (2024-07-29)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.11) pkg> st
Status `~/.julia/environments/v1.11/Project.toml`
  [89398ba2] LocalRegistry v0.5.7
  [295af30f] Revise v3.5.18

(@v1.11) pkg> add OhMyREPL
   Resolving package versions...
    Updating `~/.julia/environments/v1.11/Project.toml`
  [5fb14364] + OhMyREPL v0.5.27
    Updating `~/.julia/environments/v1.11/Manifest.toml`
  [a8cc5b0e] + Crayons v4.1.1
  [1019f520] + JLFzf v0.1.7
  [692b3bcd] + JLLWrappers v1.5.0
  [70703baa] + JuliaSyntax v0.4.9
  [5fb14364] + OhMyREPL v0.5.27
  [b98c9c47] + Pipe v1.3.0
  [21216c6a] + Preferences v1.4.3
⌅ [214eeab7] + fzf_jll v0.43.0+0
        Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`
Precompiling project...
  ✗ OhMyREPL
  0 dependencies successfully precompiled in 143 seconds. 46 already precompiled.
  1 dependency errored.
  For a report of the errors see `julia> err`. To retry use `pkg> precompile`

julia> err
PkgPrecompileError: The following 1 direct dependency failed to precompile:

OhMyREPL

Failed to precompile OhMyREPL [5fb14364-9ced-5910-84b2-373655c76a03] to "/Users/jonalmeriksen/.julia/compiled/v1.11/OhMyREPL/jl_w0RPzz".
ERROR: LoadError: failed process: Process(`/Users/jonalmeriksen/.julia/juliaup/julia-1.11.0-rc2+0.aarch64.apple.darwin14/bin/julia -O0 --trace-compile=/var/folders/32/r44x54pn3fq40v94rc16yqwh0000gn/T/jl_TgRqxX --cpu-target=native --project=/Users/jonalmeriksen/.julia/environments/v1.11/Project.toml --compiled-modules=no --startup-file=no -i --color=yes`, ProcessExited(1)) [1]

Stacktrace:
  [1] pipeline_error
    @ ./process.jl:598 [inlined]
  [2] (::OhMyREPL.var"#7#12"{Set{String}, Base.DevNull, String, String, String, String, OhMyREPL.var"#julia_exepath#10", String})(precompile_file::String, precompile_file_h::IOStream)
    @ OhMyREPL ~/.julia/packages/OhMyREPL/gPPKm/src/precompile.jl:88
  [3] mktemp(fn::OhMyREPL.var"#7#12"{Set{String}, Base.DevNull, String, String, String, String, OhMyREPL.var"#julia_exepath#10", String}, parent::String)
    @ Base.Filesystem ./file.jl:790
  [4] mktemp
    @ ./file.jl:788 [inlined]
  [5] (::OhMyREPL.var"#generate_precompile_statements#11"{String, String, String, String, OhMyREPL.var"#julia_exepath#10", String})()
    @ OhMyREPL ~/.julia/packages/OhMyREPL/gPPKm/src/precompile.jl:28
  [6] top-level scope
    @ ~/.julia/packages/OhMyREPL/gPPKm/src/precompile.jl:111
  [7] include(mod::Module, _path::String)
    @ Base ./Base.jl:558
  [8] include
    @ ~/.julia/packages/OhMyREPL/gPPKm/src/OhMyREPL.jl:6 [inlined]
  [9] top-level scope
    @ ~/.julia/packages/OhMyREPL/gPPKm/src/OhMyREPL.jl:143
 [10] include
    @ ./Base.jl:558 [inlined]
 [11] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:2749
 [12] top-level scope
    @ stdin:4
in expression starting at /Users/jonalmeriksen/.julia/packages/OhMyREPL/gPPKm/src/precompile.jl:1
in expression starting at /Users/jonalmeriksen/.julia/packages/OhMyREPL/gPPKm/src/OhMyREPL.jl:2
in expression starting at stdin:
```

**Comment by KristofferC** [comment]
Yeah, there is an issue open about it. I'll see if I can fix it.

**Comment by jonalm** [comment]
FWIW, it works on Windows for rc2.

**Comment by kobusherbst** [comment]
Same problem on macOS 14.5
